
import unicodedata

PAIS_NOME_CODIGO= {
    "Andorra": "AD",
    "Emirados Árabes Unidos": "AE",
    "Afeganistão": "AF",
    "Antígua e Barbuda": "AG",
    "Anguilla": "AI",
    "Albânia": "AL",
    "Armênia": "AM",
    "Angola": "AO",
    "Antártida": "AQ",
    "Argentina": "AR",
    "Samoa Americana": "AS",
    "Áustria": "AT",
    "Austrália": "AU",
    "Aruba": "AW",
    "Ilhas Aland": "AX",
    "Azerbaijão": "AZ",
    "Bósnia e Herzegovina": "BA",
    "Barbados": "BB",
    "Bangladesh": "BD",
    "Bélgica": "BE",
    "Burkina Faso": "BF",
    "Bulgária": "BG",
    "Bahrein": "BH",
    "Burundi": "BI",
    "Benin": "BJ",
    "São Bartolomeu": "BL",
    "Bermudas": "BM",
    "Brunei": "BN",
    "Bolívia": "BO",
    "Bonaire, Santo Eustáquio e Saba": "BQ",
    "Brasil": "BR",
    "Bahamas": "BS",
    "Butão": "BT",
    "Ilha Bouvet": "BV",
    "Botswana": "BW",
    "Belarus": "BY",
    "Belize": "BZ",
    "Canadá": "CA",
    "Ilhas Cocos (Keeling)": "CC",
    "República Democrática do Congo": "CD",
    "República Centro-Africana": "CF",
    "República do Congo": "CG",
    "Suíça": "CH",
    "Costa do Marfim": "CI",
    "Ilhas Cook": "CK",
    "Chile": "CL",
    "Camarões": "CM",
    "China": "CN",
    "Colômbia": "CO",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Cabo Verde": "CV",
    "Curaçao": "CW",
    "Ilha Christmas": "CX",
    "Chipre": "CY",
    "República Checa": "CZ",
    "Alemanha": "DE",
    "Djibouti": "DJ",
    "Dinamarca": "DK",
    "Dominica": "DM",
    "República Dominicana": "DO",
    "Argélia": "DZ",
    "Equador": "EC",
    "Egito": "EG",
    "Saara Ocidental": "EH",
    "Eritreia": "ER",
    "Espanha": "ES",
    "Etiópia": "ET",
    "Finlândia": "FI",
    "Fiji": "FJ",
    "Ilhas Falkland": "FK",
    "Micronésia": "FM",
    "Ilhas Faroe": "FO",
    "França": "FR",
    "Gabão": "GA",
    "Reino Unido": "GB",
    "Granada": "GD",
    "Geórgia": "GE",
    "Guiana Francesa": "GF",
    "Guernsey": "GG",
    "Gana": "GH",
    "Gibraltar": "GI",
    "Groenlândia": "GL",
    "Gâmbia": "GM",
    "Guiné": "GN",
    "Guadalupe": "GP",
    "Guiné Equatorial": "GQ",
    "Grécia": "GR",
    "Ilhas Geórgia do Sul e Sandwich do Sul": "GS",
    "Guatemala": "GT",
    "Guam": "GU",
    "Guiné-Bissau": "GW",
    "Guiana": "GY",
    "Hong Kong": "HK",
    "Ilha Heard e Ilhas McDonald": "HM",
    "Honduras": "HN",
    "Croácia": "HR",
    "Haiti": "HT",
    "Hungria": "HU",
    "Indonésia": "ID",
    "Irlanda": "IE",
    "Israel": "IL",
    "Ilha de Man": "IM",
    "Índia": "IN",
    "Território Britânico do Oceano Índico": "IO",
    "Iraque": "IQ",
    "Irã": "IR",
    "Islândia": "IS",
    "Itália": "IT",
    "Jersey": "JE",
    "Jamaica": "JM",
    "Jordânia": "JO",
    "Japão": "JP",
    "Quênia": "KE",
    "Quirguistão": "KG",
    "Camboja": "KH",
    "Kiribati": "KI",
    "Comores": "KM",
    "São Cristóvão e Nevis": "KN",
    "Coreia do Norte": "KP",
    "Coreia do Sul": "KR",
    "Kuwait": "KW",
    "Ilhas Cayman": "KY",
    "Cazaquistão": "KZ",
    "Laos": "LA",
    "Líbano": "LB",
    "Santa Lúcia": "LC",
    "Liechtenstein": "LI",
    "Sri Lanka": "LK",
    "Libéria": "LR",
    "Lesoto": "LS",
    "Lituânia": "LT",
    "Luxemburgo": "LU",
    "Letônia": "LV",
    "Líbia": "LY",
    "Marrocos": "MA",
    "Mônaco": "MC",
    "Moldávia": "MD",
    "Montenegro": "ME",
    "São Martinho": "MF",
    "Madagascar": "MG",
    "Ilhas Marshall": "MH",
    "Macedônia do Norte": "MK",
    "Mali": "ML",
    "Myanmar": "MM",
    "Mongólia": "MN",
    "Macau": "MO",
    "Ilhas Marianas do Norte": "MP",
    "Martinica": "MQ",
    "Mauritânia": "MR",
    "Montserrat": "MS",
    "Malta": "MT",
    "Maurício": "MU",
    "Maldivas": "MV",
    "Malawi": "MW",
    "México": "MX",
    "Malásia": "MY",
    "Moçambique": "MZ",
    "Namíbia": "NA",
    "Nova Caledônia": "NC",
    "Níger": "NE",
    "Ilha Norfolk": "NF",
    "Nigéria": "NG",
    "Nicarágua": "NI",
    "Países Baixos": "NL",
    "Noruega": "NO",
    "Nepal": "NP",
    "Nauru": "NR",
    "Niue": "NU",
    "Nova Zelândia": "NZ",
    "Omã": "OM",
    "Panamá": "PA",
    "Peru": "PE",
    "Polinésia Francesa": "PF",
    "Papua Nova Guiné": "PG",
    "Filipinas": "PH",
    "Paquistão": "PK",
    "Polônia": "PL",
    "Saint Pierre e Miquelon": "PM",
    "Ilhas Pitcairn": "PN",
    "Porto Rico": "PR",
    "Palestina": "PS",
    "Portugal": "PT",
    "Palau": "PW",
    "Paraguai": "PY",
    "Qatar": "QA",
    "Reunião": "RE",
    "Romênia": "RO",
    "Sérvia": "RS",
    "Rússia": "RU",
    "Ruanda": "RW",
    "Ilhas Salomão": "SB",
    "Seicheles": "SC",
    "Suécia": "SE",
    "Singapura": "SG",
    "Eslovênia": "SI",
    "Svalbard e Jan Mayen": "SJ",
    "Eslováquia": "SK",
    "San Marino": "SM",
    "Senegal": "SN",
    "Somália": "SO",
    "Sudão do Sul": "SS",
    "São Tomé e Príncipe": "ST",
    "El Salvador": "SV",
    "Sint Maarten": "SX",
    "Síria": "SY",
    "Eswatini": "SZ",
    "Ilhas Turks e Caicos": "TC",
    "Chade": "TD",
    "Terras Austrais e Antárticas Francesas": "TF",
    "Togo": "TG",
    "Tailândia": "TH",
    "Tajiquistão": "TJ",
    "Tokelau": "TK",
    "Timor-Leste": "TL",
    "Turcomenistão": "TM",
    "Tunísia": "TN",
    "Turquia": "TR",
    "Trinidad e Tobago": "TT",
    "Tuvalu": "TV",
    "Taiwan": "TW",
    "Tanzânia": "TZ",
    "Ucrânia": "UA",
    "Uganda": "UG",
    "Ilhas Menores Distantes dos Estados Unidos": "UM",
    "Estados Unidos": "US",
    "Uruguai": "UY",
    "Uzbequistão": "UZ",
    "Vaticano": "VA",
    "São Vicente e Granadinas": "VC",
    "Venezuela": "VE",
    "Ilhas Virgens Britânicas": "VG",
    "Ilhas Virgens Americanas": "VI",
    "Vietnã": "VN",
    "Vanuatu": "VU",
    "Wallis e Futuna": "WF",
    "Kosovo": "XK",
    "Iémen": "YE",
    "Mayotte": "YT",
    "Zâmbia": "ZM",
    "Zimbábue": "ZW",
    "Desconhecido": "ZZ"
}

def normalizar_string(string):
    letras = unicodedata.normalize('NFD', string.lower())
    return u''.join(ch for ch in letras if unicodedata.category(ch) != 'Mn')

def encontrar_pais(pais):
    pais_normalizado = normalizar_string(pais)
    key = next(filter(lambda x: normalizar_string(x)==pais_normalizado,PAIS_NOME_CODIGO.keys()), 'Desconhecido')
    return PAIS_NOME_CODIGO[key]

def encontrar_cod(nomePais):
    key = next(filter(lambda k: PAIS_NOME_CODIGO[k]==nomePais,PAIS_NOME_CODIGO.keys()), None)
    if key == None:
        return 'BR'
    return PAIS_NOME_CODIGO[key]